version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: passminmeg
      MYSQL_DATABASE: root
    ports:
      - "3306:3306"

  web:
    build: .
    command: rails s -p 3000 -b '0.0.0.0'

    #データの永続化（Dockerを停止しても内容はのこる）に必要
    volumes:
      - .:/Music-record

      #コンテナ内のポートをホストの3000にマッピング
    ports:
      - "3000:3000"
    links:
      - db
