version: '3'
services:
  db:
    image: mysql:5.7
    container_name: music_record_mysql
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: passminmeg
      MYSQL_DATABASE: root
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3316:3306"

  web:
    build: .
    container_name: music_record
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    #データの永続化（Dockerを停止しても内容はのこる）に必要
    volumes:
      - .:/Music-record

      #コンテナ内のポートをホストの3000にマッピング
    ports:
      - "3000:3000"
    depends_on:
      - db
